export const CHANGE_LOADING = 'CHANGE_LOADING';
export type CHANGE_LOADING = typeof CHANGE_LOADING;

export const RECEIVE_SEARCH_HOT = 'RECEIVE_SEARCH_HOT';
export type RECEIVE_SEARCH_HOT = typeof RECEIVE_SEARCH_HOT;

export const RECEIVE_BANNERS = 'RECEIVE_BANNERS';
export type RECEIVE_BANNERS = typeof RECEIVE_BANNERS;

export const RECEIVE_SONGS_URL = 'RECEIVE_SONGS_URL';
export type RECEIVE_SONGS_URL = typeof RECEIVE_SONGS_URL;

export const RECEIVE_PERSONALIZED = 'RECEIVE_PERSONALIZED';
export type RECEIVE_PERSONALIZED = typeof RECEIVE_PERSONALIZED;

export const RECEIVE_PERSONALIZED_NEWSONG = 'RECEIVE_PERSONALIZED_NEWSONG';
export type RECEIVE_PERSONALIZED_NEWSONG = typeof RECEIVE_PERSONALIZED_NEWSONG;

export const RECEIVE_PLAYLIST_DETAIL = 'RECEIVE_PLAYLIST_DETAIL';
export type RECEIVE_PLAYLIST_DETAIL = typeof RECEIVE_PLAYLIST_DETAIL;

export const RECEIVE_CURRENT_SONG_URL = 'RECEIVE_CURRENT_SONG_URL';
export type RECEIVE_CURRENT_SONG_URL = typeof RECEIVE_CURRENT_SONG_URL;

export const RECEIVE_SONGS = 'RECEIVE_SONGS';
export type RECEIVE_SONGS = typeof RECEIVE_SONGS;

export const RECEIVE_MV = 'RECEIVE_MV';
export type RECEIVE_MV = typeof RECEIVE_MV;

export const RECEIVE_VIDEO = 'RECEIVE_VIDEO';
export type RECEIVE_VIDEO = typeof RECEIVE_VIDEO;

export const RECEIVE_MY_PLAYLIST = 'RECEIVE_MY_PLAYLIST';
export type RECEIVE_MY_PLAYLIST = typeof RECEIVE_MY_PLAYLIST;

export const RECEIVE_USERDETAIL = 'RECEIVE_USERDETAIL';
export type RECEIVE_USERDETAIL = typeof RECEIVE_USERDETAIL;

/**
 * @param {Player use}
 */
export const CONTROLL_CHANGE_PAUSED = 'CONTROLL_CHANGE_PAUSED';
export type CONTROLL_CHANGE_PAUSED = typeof CONTROLL_CHANGE_PAUSED;

export const CONTROLL_CURRENT_DETAIL = 'CONTROLL_CURRENT_DETAIL';
export type CONTROLL_CURRENT_DETAIL = typeof CONTROLL_CURRENT_DETAIL;

export const NEXT_SONG = 'NEXT_SONG';
export type NEXT_SONG = typeof NEXT_SONG;

export const LAST_SONG = 'LAST_SONG';
export type LAST_SONG = typeof LAST_SONG;

export const RECEIVE_PLAYER_SONGS = 'RECEIVE_PLAYER_SONGS';
export type RECEIVE_PLAYER_SONGS = typeof RECEIVE_PLAYER_SONGS;

export const CONTROLL_CURRENT_SONG = 'CONTROLL_CURRENT_SONG';
export type CONTROLL_CURRENT_SONG = typeof CONTROLL_CURRENT_SONG;

export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS';
export type CHANGE_LOGIN_STATUS = typeof CHANGE_LOGIN_STATUS;

export const SAVE_USERINFO = 'SAVE_USERINFO';
export type SAVE_USERINFO = typeof SAVE_USERINFO;

export const RECEIVE_SONG_LYC = 'RECEIVE_SONG_LYC';
export type RECEIVE_SONG_LYC = typeof RECEIVE_SONG_LYC;

export const CHAGNE_PLAY_MOOD = 'CHAGNE_PLAY_MOOD';
export type CHAGNE_PLAY_MOOD = typeof CHAGNE_PLAY_MOOD;

export const RECEIVE_SEARCH_DATA = 'RECEIVE_SEARCH_DATA';
export type RECEIVE_SEARCH_DATA = typeof RECEIVE_SEARCH_DATA;
