export const CHANGE_LOADING = 'CHANGE_LOADING';
export type CHANGE_LOADING = typeof CHANGE_LOADING;

export const RECEIVE_SEARCH_HOT = 'RECEIVE_SEARCH_HOT';
export type RECEIVE_SEARCH_HOT = typeof RECEIVE_SEARCH_HOT;

export const RECEIVE_BANNERS = 'RECEIVE_BANNERS';
export type RECEIVE_BANNERS = typeof RECEIVE_BANNERS;