export const CHANGE_LOADING = 'CHANGE_LOADING';
export type CHANGE_LOADING = typeof CHANGE_LOADING;

export const RECEIVE_SEARCH_HOT = 'RECEIVE_SEARCH_HOT';
export type RECEIVE_SEARCH_HOT = typeof RECEIVE_SEARCH_HOT;

export const RECEIVE_BANNERS = 'RECEIVE_BANNERS';
export type RECEIVE_BANNERS = typeof RECEIVE_BANNERS;

export const RECEIVE_SONGS_URL = 'RECEIVE_SONGS_URL';
export type RECEIVE_SONGS_URL = typeof RECEIVE_SONGS_URL;

export const RECEIVE_PERSONALIZED = 'RECEIVE_PERSONALIZED';
export type RECEIVE_PERSONALIZED = typeof RECEIVE_PERSONALIZED;

export const RECEIVE_PERSONALIZED_NEWSONG = 'RECEIVE_PERSONALIZED_NEWSONG';
export type RECEIVE_PERSONALIZED_NEWSONG = typeof RECEIVE_PERSONALIZED_NEWSONG;