/**
 * @param {UIImage}
 * 
 * --- UI IMAGE UTIL ---
 */

const UIImage = {
	home_password_1: require("../img/home_password_1.png"),
	bt_messsge_on: require("../img/bt_messsge_on.png"),
	pic_bigpic: require("../img/pic_bigpic.png"),
	pic_smallpic: require("../img/pic_smallpic.png"),
	bt_shop_scan: require("../img/bt_shop_scan.png"),
	banner_1: require("../img/banner_1.png"),
	bg_mymoney: require("../img/bg_mymoney.png"),
	bg_success: require("../img/bg_success.png"),
	bg_waitting: require("../img/bg_waitting.png"),
	bt_add: require("../img/bt_add.png"),
	bt_adds: require("../img/bt_adds.png"),
	bt_home_scan: require("../img/bt_home_scan.png"),
	bt_home_wave: require("../img/bt_home_wave.png"),
	bt_logout: require("../img/bt_logout.png"),
	bt_messsge: require("../img/bt_messsge.png"),
	bt_minus: require("../img/bt_minus.png"),
	bt_qrcode: require("../img/bt_qrcode.png"),
	bt_qrcode_white: require("../img/bt_qrcode_white.png"),
	bt_return_black: require("../img/bt_return_black.png"),
	bt_return_white: require("../img/bt_return_white.png"),
	bt_scan_white: require("../img/bt_scan_white.png"),
	bt_screen: require("../img/bt_screen.png"),
	bt_takeup: require("../img/bt_takeup.png"),
	bt_takeup_black: require("../img/bt_takeup_black.png"),
	bt_takeup_blue: require("../img/bt_takeup_blue.png"),
	bt_triangle_1: require("../img/bt_triangle_1.png"),
	bt_triangle_2: require("../img/bt_triangle_2.png"),
	bt_triangle_gray: require("../img/bt_triangle_gray.png"),
	bt_user: require("../img/bt_user.png"),
	dot: require("../img/dot.png"),
	dot_on: require("../img/dot_on.png"),
	ic_address: require("../img/ic_address.png"),
	ic_car_off: require("../img/ic_car_off.png"),
	ic_car_on: require("../img/ic_car_on.png"),
	ic_check: require("../img/ic_check.png"),
	ic_check_off: require("../img/ic_check_off.png"),
	ic_eye_close: require("../img/ic_eye_close.png"),
	ic_eye_open: require("../img/ic_eye_open.png"),
	ic_login_close: require("../img/ic_login_close.png"),
	ic_mask: require("../img/ic_mask.png"),
	ic_next: require("../img/ic_next.png"),
	ic_plus: require("../img/ic_plus.png"),
	ic_position: require("../img/ic_position.png"),
	ic_reduce: require("../img/ic_reduce.png"),
	ic_scan_black: require("../img/ic_scan_black.png"),
	ic_search: require("../img/ic_search.png"),
	ic_weixin: require("../img/ic_weixin.png"),
	login_message: require("../img/login_message.png"),
	login_password: require("../img/login_password.png"),
	login_user: require("../img/login_user.png"),
	pic_background: require("../img/pic_background.png"),
	pic_gradual: require("../img/pic_gradual.png"),
	pic_head: require("../img/pic_head.png"),
	pic_head_default: require("../img/pic_head_default.png"),
	pic_map: require("../img/pic_map.png"),
	pic_nothing: require("../img/pic_nothing.png"),
	pic_saoma_line_blue: require("../img/pic_saoma_line_blue.png"),
	pic_saoyisao_blue: require("../img/pic_saoyisao_blue.png"),
	pic_shadow_1: require("../img/pic_shadow_1.png"),
	pic_shadow_2: require("../img/pic_shadow_2.png"),
	pic_smile: require("../img/pic_smile.png"),
	pic_stripe: require("../img/pic_stripe.png"),
	pic_tianwen_l: require("../img/pic_tianwen_l.png"),
	pic_tiaowen_r: require("../img/pic_tiaowen_r.png"),
	pic_user_mask: require("../img/pic_user_mask.png"),
	home_address : require("../img/home_address.png"),
	home_bg : require("../img/home_bg.png"),
	home_contacts : require("../img/home_contacts.png"),
	home_integral : require("../img/home_integral.png"),
	home_password : require("../img/home_password.png"),
	home_set : require("../img/home_set.png"),
	home_share : require("../img/home_share.png"),
	ic_home_coupon : require("../img/ic_home_coupon.png"),
	ic_home_discount : require("../img/ic_home_discount.png"),
	ic_home_give : require("../img/ic_home_give.png"),
	ic_home_hot : require("../img/ic_home_hot.png"),
	ic_home_integral : require("../img/ic_home_integral.png"),
	ic_home_jfsc : require("../img/ic_home_jfsc.png"),
	ic_home_life : require("../img/ic_home_life.png"),
	ic_home_selected : require("../img/ic_home_selected.png"),
	ic_home_shopping : require("../img/ic_home_shopping.png"),
	ic_home_snacks : require("../img/ic_home_snacks.png"),
	ic_home_whole : require("../img/ic_home_whole.png"),
	nav_find : require("../img/nav_find.png"),
	nav_find_on : require("../img/nav_find_on.png"),
	nav_home : require("../img/nav_home.png"),
	nav_home_on : require("../img/nav_home_on.png"),
	nav_integral : require("../img/nav_integral.png"),
	nav_integral_on : require("../img/nav_integral_on.png"),
	nav_mine : require("../img/nav_mine.png"),
	nav_mine_on : require("../img/nav_mine_on.png"),
	nav_scan : require("../img/nav_scan.png"),
	pic_women: require("../img/pic_women.png"),
	pic_man: require("../img/pic_man.png"),
}

export default UIImage;